fieldLayouts:
  d86979c9-3a6d-4414-94e5-740a83004249:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a625b38c-0014-407b-906a-fbaf8f242b3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e47b95bf-7a74-49e3-afa3-a938bd733ef7 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73fb60c9-cf55-4350-aa14-a2fcc8428a5d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adcea45e-bf40-4faf-b0c8-4ce089696971 # Lead Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1eef252a-37e3-4fd5-b568-1dde952f360f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d05f4009-0b38-4065-a1b1-65221aa65e63 # Hero Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5b64bea-a1c5-4e7a-9441-a431a6f45999
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c620460-c590-4098-b23a-de518414d7c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06209fac-a320-462f-a584-bb31888d7fc3
        userCondition: null
handle: topics
name: 'Content Topics'
