description: null
handle: siteOwner
name: 'Site Owner'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:a9eefedb-b175-4baa-a9ee-903aa94e9c9b' # Content Editor
  - 'assignusergroup:e511df66-41ea-4d8f-bfa5-538fec0fc45f' # Site Owner
  - assignuserpermissions
  - deleteusers
  - 'editsite:34463b82-dd3f-441c-b9c6-59c351e847aa' # Wireframe Site
  - editusers
  - impersonateusers
  - moderateusers
  - registerusers
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:php-info'
  - 'utility:queue-manager'
  - 'utility:system-messages'
  - 'utility:system-report'
