fieldLayouts:
  453ddd73-5986-4ead-a737-8a2775163520:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 52e15e4f-4d53-4b8d-8106-654d6e621e0c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eeefc0c2-8e1c-4607-94af-2574c13d09fe
        userCondition: null
fs: staticAssets
handle: staticAssets
name: 'Static Assets'
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
