tabs:
  -
    elements:
      -
        fieldUid: b181050f-eab8-45f0-906a-c8241c2d3cf2 # Show Block Meta
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: 'Content Admin'
    sortOrder: 1
