defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  34463b82-dd3f-441c-b9c6-59c351e847aa: # Craft
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
