field: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Blocks
fieldLayouts:
  6dad8a0b-5ca1-4007-a9e7-52e3a6af16d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4ebdb729-ea5a-4ff4-b10f-e4b2d0da2292 # Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab9bf92b-9057-4e4d-b4ad-8612f449095b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cace9df3-a737-44e2-8ad5-ad5495c87c33
        userCondition: null
fields:
  4ebdb729-ea5a-4ff4-b10f-e4b2d0da2292: # Entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # FAQs
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # News
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Pages
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: entries
name: Entry
sortOrder: 3
