field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  740cffdc-873e-42da-ab3b-9f6a01003077:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b911f8a5-3dbc-4aa9-8be2-9eb2c9c8a2ed # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8681f02a-2210-4f45-9404-ca6b2379ba31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1609989-70ec-42e9-a2d0-ce1a902593c7 # Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33fad8c0-e55c-48fa-a820-4a3b1170da8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4d11cc3-ff49-4b48-ad2a-d5a30294d552 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1fff6d4-13c6-4486-9253-3b57c0938486
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cd660f34-a88e-4f6f-a63d-dac487f3c1b3 # Anchor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a4744a-f5be-4ecd-a39e-b056d94bedd2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 07fd881e-0862-439b-a7f3-7232454c1947 # Layout Variations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7721d025-f700-44b7-8ab2-c920c8f2f7a5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b99b85fc-06c0-4960-bcda-7f07690ef20d # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b327ec65-2b08-42c3-99b7-28846c7708d8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b947d0e1-da59-4426-bb04-17175245afa2 # Edges
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77f51075-54de-4ad6-a232-9d1d1d844ec8
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: d1aaa0a6-b73f-406c-bc76-8576bc43d59b
        userCondition: null
fields:
  07fd881e-0862-439b-a7f3-7232454c1947: # Layout Variations
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'How the content lays out inside the block.'
    name: 'Layout Variations'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Cards
            -
              - value
              - cards
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Carousel
            -
              - value
              - carousel
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a1609989-70ec-42e9-a2d0-ce1a902593c7: # Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: Items
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources:
        - 'section:a52e2b08-2e30-4b00-8784-4104c409d3ed' # FAQs
        - 'section:3721b4d6-42d5-41fc-b6e7-76204b42c91a' # News
        - 'section:650e7d1d-63e5-42f9-b3ab-4febfb502723' # Pages
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b99b85fc-06c0-4960-bcda-7f07690ef20d: # Background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: 'How the block background should look.'
    name: Background
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Band
            -
              - value
              - band
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Box
            -
              - value
              - box
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Outline
            -
              - value
              - outline
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b911f8a5-3dbc-4aa9-8be2-9eb2c9c8a2ed: # Intro Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Intro Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b947d0e1-da59-4426-bb04-17175245afa2: # Edges
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: edges
    instructions: 'How the block interacts with elements around it.'
    name: Edges
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Line Before'
            -
              - value
              - lineBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Gap Before'
            -
              - value
              - noGapBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Extra Space'
            -
              - value
              - extraSpace
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c4d11cc3-ff49-4b48-ad2a-d5a30294d552: # Eyebrow
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: 'A small line of sub-text that appears above a headline.'
    name: Eyebrow
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cd660f34-a88e-4f6f-a63d-dac487f3c1b3: # Anchor Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Creates a URL `#hash-tag` for linking directly to this block'
    name: 'Anchor Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: '#example-link'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: entries
name: 'Embedded Entries'
sortOrder: 5
