field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  315c14e5-c16f-44d7-b169-8e74920df021:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 26431232-d9c5-41cd-9cad-3647ec59afbd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41be2032-3dea-4fe0-adb5-c0c7eaf8fcd1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 055d3887-062f-4180-bac4-65a9670f0440
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ce93d6f-29e0-4ac4-9ec6-fe068dfc2dff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8196605-52ba-47d2-ba43-8dc77de92903
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2148e91a-9dca-400f-a187-d950e8770650
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9844b6dc-6dbb-4203-9eec-5507fcee91f7
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c24c8bd-8b10-47c4-b679-8b9ff820fca6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 09e29257-428d-40f2-81a3-c594a739de68
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13497fc7-23d7-4c7d-bea4-3e969338d002
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9305104a-d7ea-4f07-b6a5-4f02e3232cbd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9fd208b-643b-4416-9cf4-2503b4565435
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d29c3934-5af7-4d49-9515-9dea41e6d3c2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da780989-1020-4dc5-af0a-bde0cb88b420
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: dd06e3eb-fff5-4c16-b219-b53867573f86
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 860dee8f-67ee-403c-b90c-9c8a01147044
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 43048f2c-3b11-44e7-8c32-29d991c819cc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b199b5e-c75a-4a5a-ab8a-670cb0e73e95
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: b835d646-e8f5-48a6-9bed-53d86f303a3f
        userCondition: null
fields:
  09e29257-428d-40f2-81a3-c594a739de68:
    columnSuffix: jidmezte
    contentColumnType: string
    fieldGroup: null
    handle: order
    instructions: null
    name: Order
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Most Recent'
            -
              - value
              - mostRecent
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Random
            -
              - value
              - random
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  055d3887-062f-4180-bac4-65a9670f0440:
    columnSuffix: afglrhoj
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      config: blocks/listing-formats.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  9844b6dc-6dbb-4203-9eec-5507fcee91f7:
    columnSuffix: ajwnsacs
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: 12
      max: null
      min: -1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  43048f2c-3b11-44e7-8c32-29d991c819cc:
    columnSuffix: wbmfjcuh
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: null
    name: Spacing
    searchable: false
    settings:
      config: blocks/spacing.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  9305104a-d7ea-4f07-b6a5-4f02e3232cbd:
    columnSuffix: sfmlstuo
    contentColumnType: boolean
    fieldGroup: null
    handle: hasSearch
    instructions: null
    name: 'Include Search?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  26431232-d9c5-41cd-9cad-3647ec59afbd:
    columnSuffix: hyzrszln
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d29c3934-5af7-4d49-9515-9dea41e6d3c2:
    columnSuffix: qqtvixca
    contentColumnType: boolean
    fieldGroup: null
    handle: hasPagination
    instructions: null
    name: 'Include Pagination?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  dd06e3eb-fff5-4c16-b219-b53867573f86:
    columnSuffix: fjmlbprp
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: null
    name: Background
    searchable: false
    settings:
      config: blocks/backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  e8196605-52ba-47d2-ba43-8dc77de92903:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: topic
    instructions: null
    name: 'Filter by Topic'
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: 'Choose topic'
      showSiteMenu: false
      source: 'taggroup:309b4130-a979-4b2c-8a72-971bbeb15553' # Content Topics
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
handle: faqListing
name: 'Faq Listing'
sortOrder: 9
