field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Blocks
fieldLayouts:
  564ddb22-070a-4f59-9191-678a9a6aa04c:
    tabs:
      -
        elements:
          -
            fieldUid: e2cdac24-87bd-4a5b-be66-d991b0323794 # Fragment(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  e2cdac24-87bd-4a5b-be66-d991b0323794: # Fragment(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fragments
    instructions: ''
    name: Fragment(s)
    searchable: false
    settings:
      allowSelfRelations: false
      entryTypes:
        - 174cd975-f457-4998-8bcc-3d25963f9c3b # Content Fragment
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:89093e20-515d-4e3c-b4c4-c6733d8ab56f' # Fragments
      targetSiteId: null
      userGroups: null
      users: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: nfourtythree\entriessubset\fields\EntriesSubsetField
handle: fragment
name: Fragment
sortOrder: 9
