field: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Blocks
fieldLayouts:
  8729952a-d918-4fb7-bf8e-fad40d92d3f5:
    tabs:
      -
        elements:
          -
            fieldUid: 3abe1fa4-77c1-4d66-a3da-ad8dc475b818 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 38b98344-6260-45e3-92ea-d455cfa4afe1 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 751770b9-039b-4d3b-8f92-3e31d5c0fba9 # Anchor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f800cb7c-e505-4e86-ae6a-31a286813755 # Layout Variations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 267e0240-5cf1-4d41-b3ed-86fb8328dc1a # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: c4e2b9d0-07cf-41e9-9dc7-2d4e215bd72c # Edges
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  3abe1fa4-77c1-4d66-a3da-ad8dc475b818: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Used to create a large headline break between blocks.'
    name: Headline
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Headline.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  38b98344-6260-45e3-92ea-d455cfa4afe1: # Eyebrow
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: 'A small line of sub-text that appears above a headline.'
    name: Eyebrow
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Headline.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  267e0240-5cf1-4d41-b3ed-86fb8328dc1a: # Background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: 'How the block background should look.'
    name: Background
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Band
            -
              - value
              - band
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Box
            -
              - value
              - box
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Outline
            -
              - value
              - outline
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  751770b9-039b-4d3b-8f92-3e31d5c0fba9: # Anchor Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Creates a URL `#hash-tag` for linking directly to this block'
    name: 'Anchor Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c4e2b9d0-07cf-41e9-9dc7-2d4e215bd72c: # Edges
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: edges
    instructions: 'How the block interacts with elements around it.'
    name: Edges
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Line Before'
            -
              - value
              - lineBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Gap Before'
            -
              - value
              - noGapBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Extra Space'
            -
              - value
              - extraSpace
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f800cb7c-e505-4e86-ae6a-31a286813755: # Layout Variations
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'How the content lays out inside the block.'
    name: 'Layout Variations'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: headline
name: Headline
sortOrder: 1
