field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  4b0e5059-247d-4ef8-a8a6-3d1c7461be34:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa5de47f-bd21-4e66-9e6b-93f174062abc # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f037bcf9-aaf4-45cd-90c7-d310d4f4679c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de3083f1-a02b-4884-ae77-ddd215b34e40 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c6dbddb-f57b-44ad-b265-69503e9f8842
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1edf3767-b37f-430e-8ffd-4bd1a3b9f478 # Anchor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49a42673-9cbc-43b4-b5db-09e356a96248
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7b0a973f-bff0-4f46-bfb0-b6a50c8fe28a # Layout Variations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59b3fdec-f245-4581-84b4-f2a9c7597db8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b90dc7a3-3d38-40c1-81e0-0ff813fb6fd9 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 601a0eb8-a158-4297-9942-72da6f94f1f6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f2bf26d7-ca02-4ca1-be4f-08d37fad24b4 # Edges
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ab9b1bc-e91f-4b65-8e17-7bf8c68587fb
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 06fcfa84-a4b0-40d3-9fa4-5e8e032778cd
        userCondition: null
fields:
  1edf3767-b37f-430e-8ffd-4bd1a3b9f478: # Anchor Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Creates a URL `#hash-tag` for linking directly to this block'
    name: 'Anchor Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: '#example-link'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7b0a973f-bff0-4f46-bfb0-b6a50c8fe28a: # Layout Variations
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'How the content lays out inside the block.'
    name: 'Layout Variations'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Circles
            -
              - value
              - circles
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Gallery
            -
              - value
              - gallery
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Carousel
            -
              - value
              - carousel
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  aa5de47f-bd21-4e66-9e6b-93f174062abc: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image(s)
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b90dc7a3-3d38-40c1-81e0-0ff813fb6fd9: # Background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: 'How the block background should look.'
    name: Background
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Band
            -
              - value
              - band
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Box
            -
              - value
              - box
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Outline
            -
              - value
              - outline
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  de3083f1-a02b-4884-ae77-ddd215b34e40: # Eyebrow
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: 'A small line of sub-text that appears above a headline.'
    name: Eyebrow
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f2bf26d7-ca02-4ca1-be4f-08d37fad24b4: # Edges
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: edges
    instructions: 'How the block interacts with elements around it.'
    name: Edges
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Line Before'
            -
              - value
              - lineBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Gap Before'
            -
              - value
              - noGapBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Extra Space'
            -
              - value
              - extraSpace
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: image
name: Image
sortOrder: 4
