field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Blocks
fieldLayouts:
  4b0e5059-247d-4ef8-a8a6-3d1c7461be34:
    tabs:
      -
        elements:
          -
            fieldUid: aa5de47f-bd21-4e66-9e6b-93f174062abc # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: de3083f1-a02b-4884-ae77-ddd215b34e40 # Block Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 1edf3767-b37f-430e-8ffd-4bd1a3b9f478 # Anchor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 7b0a973f-bff0-4f46-bfb0-b6a50c8fe28a # Layout Variations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b90dc7a3-3d38-40c1-81e0-0ff813fb6fd9 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: f2bf26d7-ca02-4ca1-be4f-08d37fad24b4 # Edges
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  1edf3767-b37f-430e-8ffd-4bd1a3b9f478: # Anchor Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'The a URL `#hash-tag` for jumping to this part of the entry.'
    name: 'Anchor Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: '#example-link'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7b0a973f-bff0-4f46-bfb0-b6a50c8fe28a: # Layout Variations
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'How the content lays out inside the block.'
    name: 'Layout Variations'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Gallery
            -
              - value
              - gallery
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Carousel
            -
              - value
              - carousel
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  aa5de47f-bd21-4e66-9e6b-93f174062abc: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Image(s)
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Choose Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b90dc7a3-3d38-40c1-81e0-0ff813fb6fd9: # Background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: 'How the block background should look.'
    name: Background
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Band
            -
              - value
              - band
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Box
            -
              - value
              - box
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Outline
            -
              - value
              - outline
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  de3083f1-a02b-4884-ae77-ddd215b34e40: # Block Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'Use as a section headline above the primary content of this block.'
    name: 'Block Headline'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Headline.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f2bf26d7-ca02-4ca1-be4f-08d37fad24b4: # Edges
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: edges
    instructions: 'How the block interacts with elements around it.'
    name: Edges
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Line Before'
            -
              - value
              - lineBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Gap Before'
            -
              - value
              - noGapBefore
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Extra Space'
            -
              - value
              - extraSpace
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: image
name: Image
sortOrder: 4
