field: 0cf8a6fe-e260-4ded-9320-9db2b141edcc # Listing Block
fieldLayouts:
  a08af1ae-a627-450a-8b50-2e6d5b29b245:
    tabs:
      -
        elements:
          -
            fieldUid: c25e161a-2f9c-406c-9ace-21fa7f000c4a # Limit
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 29f0f7bf-a7d4-4015-9ea2-cfd8f1530b1b # Has Search?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  29f0f7bf-a7d4-4015-9ea2-cfd8f1530b1b: # Has Search?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hasSearch
    instructions: ''
    name: 'Has Search?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c25e161a-2f9c-406c-9ace-21fa7f000c4a: # Limit
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: ''
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: 6
      max: null
      min: 1
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: news
name: News
sortOrder: 1
