field: 0cf8a6fe-e260-4ded-9320-9db2b141edcc # Listing Block
fieldLayouts:
  a08af1ae-a627-450a-8b50-2e6d5b29b245:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c25e161a-2f9c-406c-9ace-21fa7f000c4a # Limit
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d36170ef-8a2f-474d-9f6b-ae1c3340faff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 29f0f7bf-a7d4-4015-9ea2-cfd8f1530b1b # Has Search?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef40e410-c600-447a-bf04-d1281c8f19cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e0671a7-eba0-42c5-a5ab-2b30a6fc1bf6 # Layout
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d50ad6c-86dc-4ec5-a9d9-69f1c38b7489
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5f60d17b-cbec-4677-8f2e-9e7d7081c2fc
        userCondition: null
fields:
  2e0671a7-eba0-42c5-a5ab-2b30a6fc1bf6: # Layout
    columnSuffix: hujeyyhb
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'How do you want to display the individual records on the page?'
    name: Layout
    searchable: false
    settings:
      config: blocks/listing-formats.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  29f0f7bf-a7d4-4015-9ea2-cfd8f1530b1b: # Has Search?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hasSearch
    instructions: null
    name: 'Has Search?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c25e161a-2f9c-406c-9ace-21fa7f000c4a: # Limit
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: 6
      max: null
      min: 1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: news
name: News
sortOrder: 1
