field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  a1f0f4d1-9056-4f56-b262-8722794749a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c6677eab-6c78-4ca1-93cd-0faa266d1c45 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6017252d-7c65-4716-8587-0267805477aa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5347a201-6da8-47ff-bc5b-20a0dc63d44e # Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4043fe8b-846c-4408-af28-90d689ede417
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7506709b-79c3-40ab-b4d3-5ce0fa5ba5bc # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95c71aec-6877-427f-86ed-e1ce45dc6760
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 05fb8aa2-0c98-4cee-93c3-5ad2f2709822 # Anchor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deac4011-9701-4387-8e61-da8b1269fd8e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a1a62d7a-5173-4caf-8d92-423b6dc0dede # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6cead47-c085-40f3-975f-ce5f00b44f23
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7b72b671-dcdc-49b2-95cd-44a8e8be7cad # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9125f69-85d0-464d-a645-9adf0935f0d9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ae3f34db-5fe5-4438-86f0-377cfaebf02a # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33aeadab-024e-46c6-9f23-3bdae21f68da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6272049f-8eaf-4847-a1fc-52a1f881a7a9
        userCondition: null
fields:
  05fb8aa2-0c98-4cee-93c3-5ad2f2709822: # Anchor Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Creates a URL `#hash-tag` for linking directly to this block'
    name: 'Anchor Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: '#example-link'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7b72b671-dcdc-49b2-95cd-44a8e8be7cad: # Background
    columnSuffix: ngczrvyg
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: null
    name: Background
    searchable: false
    settings:
      config: blocks/backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  5347a201-6da8-47ff-bc5b-20a0dc63d44e: # Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: Items
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1012369959
      columns:
        __assoc__:
          -
            - 1ddd814c-a3f1-4689-bb67-33d04ad8307a # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 69c2d7dc-3df8-4df1-a444-d2ae376da00c # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fd647249-c4ea-4ade-99ab-13f9e53bba3f # Image / Icon
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_6_items}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  7506709b-79c3-40ab-b4d3-5ce0fa5ba5bc: # Eyebrow
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: 'A small line of sub-text that appears above a headline.'
    name: Eyebrow
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  a1a62d7a-5173-4caf-8d92-423b6dc0dede: # Spacing
    columnSuffix: vdailebf
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: null
    name: Spacing
    searchable: false
    settings:
      config: blocks/spacing.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  ae3f34db-5fe5-4438-86f0-377cfaebf02a: # Variant
    columnSuffix: ulxtrpcp
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      config: blocks/content-repeater.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  c6677eab-6c78-4ca1-93cd-0faa266d1c45: # Intro Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Intro Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: repeater
name: 'Content Repeater'
sortOrder: 6
