field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  1d75efde-1bad-4bf8-8155-0ddd2612c9e5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 61d7345d-34c5-4c93-8ae0-9f9b5f3b166b # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86557008-7633-4b84-9cd5-3694a9e2d137
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8eee0057-f0e3-4674-8fd8-6eae3cc9ae0d # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2964c8db-044d-4d06-9671-ccf395e27b28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f0a0dc0-db3f-49d5-9656-b61ad0d5c452 # Filter by Topic
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d4a9273-97d7-4423-b3d0-5f07c1086c43
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b6015f85-adad-474b-afb4-ac34bb560c0c # Limit
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8b6bffb-e4e9-4e2b-8287-785abe1b2905
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b161b327-4669-4d08-b51f-7b8c7091a2d4 # Order
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37f90003-f571-4b8f-9c7f-cba06d05bf96
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f981cb80-dd00-4b09-b682-78bfa0abccad # Include Search?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab165e2d-4fdd-4ae0-8ea3-faa14a3d4b70
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a479dbe3-176d-4b5b-b5e6-f6f5dab262ec # Include Pagination?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a80c2691-c238-4da8-a848-76f29a8b4e1e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0d2936c9-42b4-467f-9004-678230db8291 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 313f2e13-8943-491b-b9c0-6e7eb7929248
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 39b3d1e6-0464-44f3-803e-8bf88da46270 # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f87ddca5-5d77-45b2-892a-e01cf43cc06f
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: f55acb64-6c3a-483a-b5c1-2d0b59dd5d72
        userCondition: null
fields:
  0d2936c9-42b4-467f-9004-678230db8291: # Background
    columnSuffix: fwxmzlie
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: null
    name: Background
    searchable: false
    settings:
      config: blocks/backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  8eee0057-f0e3-4674-8fd8-6eae3cc9ae0d: # Variant
    columnSuffix: kpwsojnc
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      config: blocks/listing-formats.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  9f0a0dc0-db3f-49d5-9656-b61ad0d5c452: # Filter by Topic
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: topic
    instructions: null
    name: 'Filter by Topic'
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: 'Choose topic'
      showSiteMenu: false
      source: 'taggroup:309b4130-a979-4b2c-8a72-971bbeb15553' # Content Topics
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
  39b3d1e6-0464-44f3-803e-8bf88da46270: # Spacing
    columnSuffix: rirvtxji
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: null
    name: Spacing
    searchable: false
    settings:
      config: blocks/spacing.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  61d7345d-34c5-4c93-8ae0-9f9b5f3b166b: # Text
    columnSuffix: kwmvoeva
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  a479dbe3-176d-4b5b-b5e6-f6f5dab262ec: # Include Pagination?
    columnSuffix: twdfutkz
    contentColumnType: boolean
    fieldGroup: null
    handle: hasPagination
    instructions: null
    name: 'Include Pagination?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  b161b327-4669-4d08-b51f-7b8c7091a2d4: # Order
    columnSuffix: lppqelbx
    contentColumnType: string
    fieldGroup: null
    handle: order
    instructions: null
    name: Order
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Most Recent'
            -
              - value
              - mostRecent
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Random
            -
              - value
              - random
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  b6015f85-adad-474b-afb4-ac34bb560c0c: # Limit
    columnSuffix: mcovhmgu
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: 12
      max: null
      min: -1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  f981cb80-dd00-4b09-b682-78bfa0abccad: # Include Search?
    columnSuffix: ayojqsiw
    contentColumnType: boolean
    fieldGroup: null
    handle: hasSearch
    instructions: null
    name: 'Include Search?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: tagListing
name: 'Tag Listing'
sortOrder: 10
