field: a35a0beb-0cf7-4a2b-9ec3-91e953a18116 # Sidebar Blocks
fieldLayouts:
  f4131d69-6976-4341-a01d-54d1b40e0c06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dc845fdf-e229-4765-9b4c-c77ca578bd52 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a76002d-b814-4b0a-a9aa-61601ef9d468
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba46e525-f3fd-43ed-88f1-891a4ff38dbb
        userCondition: null
fields:
  dc845fdf-e229-4765-9b4c-c77ca578bd52: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 2
