field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Blocks
fieldLayouts:
  a067cac1-ec42-43cc-b56a-f98e3b5b7803:
    tabs:
      -
        elements:
          -
            fieldUid: 20aa7fd2-2f1f-4b3f-b505-a14c1c3cc164 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 7574f2c5-ebea-4c7c-9efb-fabe0fc82275 # Headline Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 1d242d6f-f863-4979-b2af-bb1da5c2aee2 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dda1fa64-dd45-42b6-8df9-476cbac15152 # Image(s)
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c9c14235-dfc3-4c81-bb97-f3e3be70fb14 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b0be437c-c9b7-4725-b61e-01ae79d26892 # Layout Variations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: e8279648-aafc-4293-a410-7e3c587f89c2 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: c2aae972-6c74-45e4-a721-cb093d6508db # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 54aa6fb8-4a59-4704-9956-2c47eb2f5ceb # Anchor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  1d242d6f-f863-4979-b2af-bb1da5c2aee2: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  20aa7fd2-2f1f-4b3f-b505-a14c1c3cc164: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: BoldOnly.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  54aa6fb8-4a59-4704-9956-2c47eb2f5ceb: # Anchor Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Used to create links that jump to a specific part of the page.'
    name: 'Anchor Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: '#example-link'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7574f2c5-ebea-4c7c-9efb-fabe0fc82275: # Headline Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headlineStyle
    instructions: ''
    name: 'Headline Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b0be437c-c9b7-4725-b61e-01ae79d26892: # Layout Variations
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Some components can have different layout variations.'
    name: 'Layout Variations'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Image Right'
            -
              - value
              - imageRight
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Image Left'
            -
              - value
              - imageLeft
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c2aae972-6c74-45e4-a721-cb093d6508db: # Background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: 'Some components have different background options.'
    name: Background
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c9c14235-dfc3-4c81-bb97-f3e3be70fb14: # Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 3d132a28-a031-453f-8dcf-7c2f939cb34a # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_buttons}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add Button'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  dda1fa64-dd45-42b6-8df9-476cbac15152: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Image(s)
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: '{owner.owner.type.handle}/{owner.owner.slug}/'
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e8279648-aafc-4293-a410-7e3c587f89c2: # Bottom Spacing
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: 'How much spacing appears around the component.'
    name: 'Bottom Spacing'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: textImage
name: 'Text + Image'
sortOrder: 2
