field: a4fe99b5-7832-4eb2-9833-f551177bb821 # Content Builder
fieldLayouts:
  030b6d0b-c5dc-459c-b3e0-6e508313ca31:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 07a0012a-4bdf-4aaa-8415-bbe06adaf62c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1935261-af10-4a93-9d6e-ac4e9cd50639
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e2e0830e-80f8-4dfd-8edf-45b6f917cd2d # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3ab6a2c-4965-47f8-890c-f5e000459e4e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bb08d0c0-bcc3-4d96-b172-572ca8f601a1 # Anchor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 563eb588-0587-49d9-b9fe-6772469f8f2b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0dabdba1-b0ed-4220-8bfd-115e5127ee42 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58085824-b0ac-4ccb-be35-e8f3181916d5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a7b99dca-7b58-438c-b57e-9d7965c3093b # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8819b91b-089d-4d95-b23f-752efb7df8bb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9d4f8876-987f-46fc-9042-aaf824a7131d # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ab4375b-4552-4f3d-be6c-051e5f50b17d
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 17da5594-72ac-4f5d-9596-133476199500
        userCondition: null
fields:
  0dabdba1-b0ed-4220-8bfd-115e5127ee42: # Background
    columnSuffix: dqtdfrpw
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: null
    name: Background
    searchable: false
    settings:
      config: blocks/backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  07a0012a-4bdf-4aaa-8415-bbe06adaf62c: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: allow.iframes.json
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9d4f8876-987f-46fc-9042-aaf824a7131d: # Variant
    columnSuffix: qfgjxwao
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      config: blocks/text.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  a7b99dca-7b58-438c-b57e-9d7965c3093b: # Spacing
    columnSuffix: lhqmhzea
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: null
    name: Spacing
    searchable: false
    settings:
      config: blocks/spacing.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  bb08d0c0-bcc3-4d96-b172-572ca8f601a1: # Anchor Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Creates a URL `#hash-tag` for linking directly to this block'
    name: 'Anchor Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: '#example-link'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e2e0830e-80f8-4dfd-8edf-45b6f917cd2d: # Eyebrow
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: 'A small line of sub-text that appears above a headline.'
    name: Eyebrow
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 1
