field: d05f4009-0b38-4065-a1b1-65221aa65e63 # Hero Block
fieldLayouts:
  95d89b00-d16f-4739-a893-bc7118fdb3e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1193bb1-b500-4050-8b68-a0a7bee4594f # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 834dbe1f-7223-4c42-8f85-a2d0c90841c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 468a14eb-fb24-4d42-85ea-51a108f68949 # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77234ae4-bd4c-458b-8160-c7ce2ce03346
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec26ccd6-8b77-446f-83e4-5a157ab84ee5 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47b29ed0-d72a-4b71-8929-6df841e61907
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 25414516-f079-42de-9891-f9dd403af271 # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62df11bc-39f6-447f-9ece-b024dd93def8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5252a6fb-4088-4f59-980a-0d5f910ab392 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79101fb3-3c5f-4d5f-b1c0-66f9f96c507d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fb8236c7-dc6f-45c6-b62d-6d6ffaaf1657 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da21838e-b116-4936-b3a5-42bdd92af0f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 70caaf25-ddf7-4109-b3f1-81e24c4423f5
        userCondition: null
fields:
  468a14eb-fb24-4d42-85ea-51a108f68949: # Variant
    columnSuffix: udmwrcap
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      config: blocks/textImage.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
  5252a6fb-4088-4f59-980a-0d5f910ab392: # Eyebrow
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: 'A small line of sub-text that appears above a headline.'
    name: Eyebrow
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  25414516-f079-42de-9891-f9dd403af271: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image(s)
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
        - 'volume:3c05e593-d621-444e-8fb9-ddbb1b356a43' # Static Assets
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c1193bb1-b500-4050-8b68-a0a7bee4594f: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: 'This will replace the "Title" field to act as the primary headline for the page and the SEO <h1> tag.'
    name: Headline
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Headline.json
      removeEmptyTags: true
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ec26ccd6-8b77-446f-83e4-5a157ab84ee5: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fb8236c7-dc6f-45c6-b62d-6d6ffaaf1657: # Background
    columnSuffix: rqyqbtbd
    contentColumnType: string
    fieldGroup: null
    handle: bg
    instructions: 'How the block background should look.'
    name: Background
    searchable: false
    settings:
      config: blocks/hero-backgrounds.json
    translationKeyFormat: null
    translationMethod: none
    type: trendyminds\designtokens\fields\DesignTokensField
handle: textImage
name: 'Text + Image'
sortOrder: 1
