columnSuffix: null
contentColumnType: text
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: dek
instructions: 'A short one or two sentence description or summary of the content. '
name: Dek
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Dek.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
