columnSuffix: null
contentColumnType: text
fieldGroup: 1e0f22f0-2c77-45f2-a8dd-9405520e5ce0 # Emergency Message
handle: eMsg_linkLabel
instructions: ''
name: '"Learn More" Call-to-Action'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Details / Subscribe / Buy Now / etc'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
