columnSuffix: null
contentColumnType: string
fieldGroup: 1e0f22f0-2c77-45f2-a8dd-9405520e5ce0 # Emergency Message
handle: eMsg_placement
instructions: ''
name: 'Where should it appear?'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'All Pages'
        -
          - value
          - allPages
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Home Page Only'
        -
          - value
          - homePage
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
