columnSuffix: null
contentColumnType: string
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: heroBlock
instructions: '(Optional) The entry `Title` will be used as the headline if no hero block is added.'
name: 'Hero Block'
searchable: true
settings:
  contentTable: '{{%matrixcontent_heroblock}}'
  maxBlocks: '1'
  minBlocks: '0'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
