columnSuffix: null
contentColumnType: string
fieldGroup: ea1a69ed-b5c5-46cf-a629-4435f7f7cad0 # Content Builders
handle: heroBlock
instructions: '(Optional) The entry `Title` will be used as the headline if no hero block is added.'
name: 'Hero Block'
searchable: true
settings:
  contentTable: '{{%matrixcontent_heroblock}}'
  maxBlocks: 1
  minBlocks: 0
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
