columnSuffix: null
contentColumnType: string
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: images
instructions: ''
name: 'Lead Image(s)'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
  defaultUploadLocationSubpath: '{section.handle}/{owner.slug}/'
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Choose image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:a4f97962-52de-4b53-8422-5b833d1cd5fd' # Uploads
    - 'volume:3c05e593-d621-444e-8fb9-ddbb1b356a43' # Static Assets
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
