columnSuffix: cvrpdgoz
contentColumnType: boolean
fieldGroup: ea1a69ed-b5c5-46cf-a629-4435f7f7cad0 # Content Builders
handle: showBlockMeta
instructions: 'When enabled, you will see the setting information for each content block through-out the site.'
name: 'Show Block Meta'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
