columnSuffix: null
contentColumnType: string
fieldGroup: ea1a69ed-b5c5-46cf-a629-4435f7f7cad0 # Content Builders
handle: sidebarBlocks
instructions: null
name: 'Sidebar Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_sidebarblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
