columnSuffix: null
contentColumnType: string
fieldGroup: e0dac603-c510-4bb5-8701-e25672d93744 # Common
handle: sidebarBlocks
instructions: ''
name: 'Sidebar Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_sidebarblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
