defaultPlacement: end
enableVersioning: true
handle: faqs
name: FAQs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  34463b82-dd3f-441c-b9c6-59c351e847aa: # Wireframe Site
    enabledByDefault: true
    hasUrls: true
    template: faqs/_entry
    uriFormat: 'faqs/{slug}'
  cc8cbe25-440c-439e-a58b-6515a3b420d0: # Site Guide
    enabledByDefault: true
    hasUrls: true
    template: faqs/_entry
    uriFormat: 'faqs/{slug}'
type: channel
